### ISSUE TITLE
multiple CC datasets

### ISSUE THREAD

**Issue by lescai** [hoangtn/extTADA#3]
Hi Hoang,
very interesting extension of TADA and useful functions provided in R.
In your paper 1 de-novo population and 3 case-control populations have been used: I was looking at the function and I can see that one object is passed for the de-novo and one object is passed for CC data. Each of these data frames can have more columns which correspond to annotation categories. How do you pass to the function more CC datasets like you did in the paper?
thanks for clarifying!
Francesco

**Comment by hoangtn** [comment]
Hi Francesco,

I just updated the README.md and some functions.
You can follow the format I just added in the example: extTADA_OneStep.ipynb
Best,
Hoang

**Comment by lescai** [comment]
Hi thanks very much for updating :)
In your new example you mention multiple categories, but I can still see like one population.
`N = list(dn = 1077, ca = 3157, cn = 4672)`
How do you set these values when you have - like in your paper - one category of variant, but multiple populations (where, usually, number of cases and controls are different)?
thanks again for your effort!

**Comment by hoangtn** [comment]
Hi!

You can follow here:

https://github.com/hoangtn/extTADA/blob/master/QandAfor_extTADA.md


Best,
Hoang
